### ISSUE TITLE
Permanent\disable groups

### ISSUE THREAD

**Issue by v00d00m4n** [FransBouma/ShaderToggler#10]
Would be nice if you can mark some separate groups of shaders as permanent or disabled on start.

Because its annoying to togle it every time and its better to set and forget some of groups while keep other off.

For example shader could be unified for menu and hud, its good idea to start without hiding shader, but then toggle it when level loads.

In other case some shaders could be safe to hide from start, so an option to keep something disabled permanently or just disable it for current session is nice.

Also sticky toggle would work as well, is group would have setting that will allow state to be saved, so you run game once and toggle on, it keeps for next launch, but then you toggle off and keeps that way until next toggle.

**Comment by John-Dean** [comment]
I've written a small amendment here: https://github.com/John-Dean/ShaderToggler that changes the default state to the group toggled on which is what I needed for my use case.

I know it's not a full fix, but there doesn't seem to be any plan to update this.

https://github.com/John-Dean/ShaderToggler

**Comment by blackwind** [comment]
Would you be so kind as to provide a 64-bit build as well, @John-Dean?

**Comment by John-Dean** [comment]
@blackwind As far as  I'm aware there is a 64-bit build in the releases of
that repo, at least I'm using it on a 64-bit install with no issues.

**Comment by FransBouma** [comment]
I released a 32bit version once but it was merely a one-time thing. 

ReShade made the addon extension addon64 and addon32 to signal the variant some time ago and newer versions of the addons I make have that newer extension. You can just rename it to whatever you want as long as reshade recognizes it.

**Comment by blackwind** [comment]
Interesting, thanks for the clarification, Frans!

**Comment by blackwind** [comment]
While we have you, any chance we'll see an official solution for this? I've always been curious what the use case is for defaulting to inactive. If I went to all the trouble of isolating shaders to be disabled, why wouldn't I want that done automatically in most, if not all cases?

**Comment by FransBouma** [comment]
Maybe in the future, I'm not going to implement it at this point. It's 1 key press to disable the shaders...

**Comment by blackwind** [comment]
Which is easy when you're at the computer with a keyboard, and much less so when you're on the couch with a controller. Just some food for thought.

**Comment by FransBouma** [comment]
Please don't act like this is a major issue and it needs to be fixed asap. I wrote this in my spare time, I can't just drop everything and work on this. Like I said, maybe in the future if I have time and energy to build this in. Maybe someone will send me a PR, maybe it will never happen.

**Comment by FransBouma** [comment]
Implemented in 1.2

**Comment by FransBouma** [comment]
1.2 is now available
