### ISSUE TITLE
Wolfenstein II The New Colossus Issue

### ISSUE THREAD

**Issue by godohandus** [FransBouma/ShaderToggler#15]
I install reshade, when I choose the Wolfenstein II The New Colossus exe, reshade automatically selects Vulkan and installs.

I place the shadder toggler in the folder with the ReShade.ini, same as the game's exe is in, and when I open the game it loads ok.

I go to the ShaderToggler section, choose change shadders, it goes through the frames as usual, but when finished it has (-1,0) instead of (1 out of 320) for example, and pressing the numpad keys doesn't cycle through the shaders.

I've used it for many games with no probs, usually directx 9-12, never vulkan before, am I doing something wrong?

**Comment by FransBouma** [comment]
I never tested it with Vulkan and from what I heard, it doesn't work. It's odd though as I use the Reshade API but vulkan and Reshade are always a bit of a problematic affair (what isn't with vulkan) so I don't think this is going to work...

**Comment by godohandus** [comment]
Damn, this is such a shame, 

It seems only the last step is the problem, reshade loads up fine, it includes shader toggler in the list, shader toggler cyclers through all the frames just fine, even displays the number of pipelines with pixel/vertex shaders!

Its only the edit that has some issue.

Check the in-game screenshot:  [https://i.imgur.com/W12xM6q.jpg](url)

Is there any chance this is something minor that could potentially be fixed?

**Comment by godohandus** [comment]
I also just tried it with '_Wolfenstein The New Order_', and '_Wolfenstein The Old Blood_', that use **OpenGL**, and it does the same thing with '_Wolfenstein II The New Colossus_' that uses **Vulkan**. So seems like it only works with DirectX then?, there is no chance that the OpenGL stuff can be fixed either?

**Comment by FransBouma** [comment]
I don't know what to do differently. What I do is gather which shaders are used in a draw call, which is caught by Reshade... No idea why it doesn't work in opengl, should work fine, but if it doesn't then perhaps how shaders are passed on to the addons by reshade is a bit different in opengl/vulkan than in d3d.

**Comment by FransBouma** [comment]
No plans to fix this at this moment, as Reshade should provide the same API for all 3d apis but there are apparently vital differences
