### ISSUE TITLE
Shader disabled does not stay as soon as I click Done

### ISSUE THREAD

**Issue by jrouzies-fr** [FransBouma/ShaderToggler#25]
Hello,

I can find a shader to disable, but the second I click the Done button next to the Group, the effect is back.

If I click Save first, then Done, same, and no effect reference is save in the .ini file.

**Comment by FransBouma** [comment]
You have to mark the shader. So if you walk through the shaders with e.g. numpad 1 or 2, you then have to mark it with numpad 3 (same goes for numpad 4-5 -> mark it with numpad 6). Once it's marked it'll be part of the group and saved in the ini file

**Comment by jrouzies-fr** [comment]
Oh ... my bad, I guess I need to learn how to read!

It works great, thank you
Jean-Laurent ROUZIES




Le lun. 22 juil. 2024 à 09:58, Frans Bouma ***@***.***> a
écrit :
