### ISSUE TITLE
DXVK Support 

### ISSUE THREAD

**Issue by G4Alves** [FransBouma/ShaderToggler#27]
Many reshade shaders do not work in d3d9, the most efficient way to use it is dxvk, older games suffer from exaggerated bloom and other horrible shaders that can be disabled with shadertoggler, but using dxvk it is impossible, I wanted to know if there is any way to use shadertoggler with dxvk

**Comment by FransBouma** [comment]
I target the Reshade API, so any shader that's created through reshade is interceptable but through reshade. I'm not targeting a direct API, so if dxvk uses a different route then it's not supported (nor can it be supported)
