### ISSUE TITLE
No ShaderToggler.ini file created despite clicking save

### ISSUE THREAD

**Issue by jjxann** [FransBouma/ShaderToggler#29]
Hello!

I am trying to hide UI in Dragon Age: Inquisition with ShaderToggler, and while your addon does work for the duration of that gaming session (a.k.a before I exit the game) no matter how many times I click "Save all toggled groups", nothing is actually saved. It appears no .ini file is created in the same folder as game's exe and ShaderToggler.addon64. 

Am I doing something wrong, or perhaps looking at the wrong place? Otherwise, and for the duration of that one session, I am able to make ShaderToggler work just fine! It is only the group saving bit that is causing issues to this newbie.

**Comment by FransBouma** [comment]
It might be it doesn't have save rights in the folder the game is located in. If the game is inside c:\program files\ then that's the cause.

**Comment by jjxann** [comment]
That indeed seems to have been the issue, because now, after changing game's location away from Program Files, saving works just fine. Thank you very much for your help! :)
