### ISSUE TITLE
Indiana Jones, nothing gathered

### ISSUE THREAD

**Issue by Mesyme** [FransBouma/ShaderToggler#30]
//

**Comment by FransBouma** [comment]
use vulkan, not d3d12. see: https://opm.fransbouma.com/Cameras/thegreatcircle.htm#enabling-reshade

**Comment by Mesyme** [comment]
thanks!

**Comment by Mesyme** [comment]
sorry to bother you again, I had no problem with shaderToggler on steam, but a friend of mine with gamepass can't get it to work.

he installed reshade on the gamelaunchhelper.exe file, because microsoft does not give access to TheGreatCircle.exe file (but they are in the same folder)
Created a shortcut of the file TheGreatCircle.exe and added +r_allowBlackListedLayers 1
if he put ShaderToggler.ini and ShaderToggler.addon64 in main folder with TheGreatCircle.exe game crash, but if he put the files in programData/reshade no crash, shaderToggler appear in addons tab but no working.

**Comment by FransBouma** [comment]
Sorry no idea what the reason of that could be...
