### ISSUE TITLE
dump shaders in game folder

### ISSUE THREAD

**Issue by DouglasProgramador123** [FransBouma/ShaderToggler#8]
I tried use your add-on for remove color filter and vignette in Resident Evil 2 Remake but turn game overbright too. I need manual editing hand editing shaders and dont have tools for do this in DX12 games. Only your mod closer to that in years.

**Comment by FransBouma** [comment]
My camera mod removes the vignette, which doesn't make it overly bright (by disabling it in the engine) so it must be the color filter which does that. Dumping shaders is a lot of work (and doesn't always work as well), so that's not in the scope of this addon, sorry
